package visao;

import controlador.GerenciadorInterfaceGrafica;
import dominio.Usuario;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.json.JSONObject;

public class JDialogNovoUsuario extends javax.swing.JDialog {

    private Usuario usuarioSelecionado;
    private String rua;
    private String bairro;
    private String cidade;
    private String uf;

    /**
     * Creates new form JDialogNovoUsuario
     */
    public JDialogNovoUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelFotoEscolher = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelFoto = new javax.swing.JLabel();
        labelCelular = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        btnCriar = new javax.swing.JButton();
        textFieldCelular = new javax.swing.JFormattedTextField();
        btnLimpar = new javax.swing.JButton();
        labelEmail = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        labelCEP = new javax.swing.JLabel();
        textFieldCEP = new javax.swing.JFormattedTextField();
        labelUF = new javax.swing.JLabel();
        comboBoxUF = new javax.swing.JComboBox<>();
        labelCidade = new javax.swing.JLabel();
        comboBoxCidade = new javax.swing.JComboBox<>();
        labelNumero = new javax.swing.JLabel();
        textFieldNumero = new javax.swing.JFormattedTextField();
        labelBairro = new javax.swing.JLabel();
        textFieldBairro = new javax.swing.JTextField();
        labelReferencia = new javax.swing.JLabel();
        textFieldReferencia = new javax.swing.JTextField();
        labelRua = new javax.swing.JLabel();
        textFieldRua = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Novo Usuário"));

        labelFotoEscolher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFotoEscolher.setText("Imagem");
        labelFotoEscolher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        labelFotoEscolher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFotoEscolherMouseClicked(evt);
            }
        });

        labelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNome.setText("Nome:");

        labelFoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelFoto.setText("Foto");

        labelCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCelular.setText("Celular:");

        btnCriar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept.png"))); // NOI18N
        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        try {
            textFieldCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/remove.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        labelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEmail.setText("Email:");

        labelCEP.setText("CEP:");

        try {
            textFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textFieldCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldCEPFocusLost(evt);
            }
        });

        labelUF.setText("Estado:");

        comboBoxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espírito Santo" }));

        labelCidade.setText("Cidade:");

        comboBoxCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colatina", "Serra", "Linhares", "São Matheus", "Baixo Guandu", "Marilândia" }));

        labelNumero.setText("Número:");

        labelBairro.setText("Bairro:");

        labelReferencia.setText("Referência:");

        labelRua.setText("Rua:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelFotoEscolher, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(labelNome))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(labelEmail)))
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCelular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(labelFoto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(labelBairro))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelReferencia)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldBairro)
                            .addComponent(textFieldReferencia)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelRua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelNumero)
                                .addGap(6, 6, 6)
                                .addComponent(textFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(labelCEP)
                                .addGap(6, 6, 6)
                                .addComponent(textFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(labelUF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(labelCidade)
                                .addGap(3, 3, 3)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFotoEscolher, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(labelNome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCelular))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEmail))))
                .addGap(6, 6, 6)
                .addComponent(labelFoto)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNumero)
                            .addComponent(labelCEP)
                            .addComponent(labelUF))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRua)
                            .addComponent(textFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCidade)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBairro))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelReferencia))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        if (textFieldNome.getText().equals("") || textFieldCelular.getText().equals("") || textFieldEmail.getText().equals("")|| textFieldNumero.getText().equals("") || textFieldCEP.getText().equals("")
                || comboBoxUF.getSelectedItem() == "" || comboBoxCidade.getSelectedItem() == null || textFieldBairro.getText().equals("")
                || textFieldRua.getText().equals("") || textFieldReferencia.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Cadastro de Usuário", JOptionPane.ERROR_MESSAGE);
        } else {
            String nome = textFieldNome.getText();
            String celular = textFieldCelular.getText();
            String email = textFieldEmail.getText();
            String numeroCasaS = textFieldNumero.getText();
            int numeroCasaI = Integer.parseInt(numeroCasaS);
            String cep = textFieldCEP.getText();
            String estado = comboBoxUF.getSelectedItem().toString(); //provisório
            String cidade = comboBoxCidade.getSelectedItem().toString(); //provisório
            String bairro = textFieldBairro.getText();
            String referencia = textFieldReferencia.getText();
            String rua = textFieldRua.getText();

            Usuario usuario = new Usuario(nome, celular, email, cep, cidade, estado, numeroCasaI, rua, bairro, referencia);
            GerenciadorInterfaceGrafica.getInstancia().addUsuario(usuario);

            GerenciadorInterfaceGrafica.getInstancia().setEditar(false);
            limparCampos();
            dispose();
        }
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void labelFotoEscolherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFotoEscolherMouseClicked
        JFileChooser janelaArquivo = new JFileChooser();
        janelaArquivo.setMultiSelectionEnabled(false);
        janelaArquivo.setFileFilter(new FileNameExtensionFilter("Imagens", "PNG", "GIF", "JPEG"));
        janelaArquivo.setAcceptAllFileFilterUsed(false);
        if (janelaArquivo.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File arquivo = janelaArquivo.getSelectedFile();
            Icon fotoPerfil = new ImageIcon(arquivo.getPath());
            mostrarImagem(fotoPerfil);
        }
    }//GEN-LAST:event_labelFotoEscolherMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        configurarBotoes();
    }//GEN-LAST:event_formComponentShown

    private void textFieldCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldCEPFocusLost
        try {
            String ender = consultarCEP(textFieldCEP.getText());
            if (ender != null) {
                textFieldRua.setText(rua);
                textFieldBairro.setText(bairro);
                comboBoxCidade.setSelectedItem(cidade);
                comboBoxUF.setSelectedItem(uf);

            } else {
                JOptionPane.showMessageDialog(this, "CEP não encontrado!", "Cadastro de Usuário", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "ERRO ao consultar CEP!", "Cadastro de Usuário", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_textFieldCEPFocusLost
    private void mostrarImagem(Icon icon) {
        ImageIcon imagem = (ImageIcon) icon;
        imagem.setImage(imagem.getImage().getScaledInstance(labelFotoEscolher.getWidth(), labelFotoEscolher.getHeight(), Image.SCALE_SMOOTH));
        labelFotoEscolher.setIcon(imagem);
        labelFotoEscolher.setText("");
    }

    private void limparCampos() {
        labelFotoEscolher.setIcon(null);
        labelFotoEscolher.setText("Imagem");
        textFieldNome.setText("");
        textFieldCelular.setText("");
        textFieldEmail.setText("");
        textFieldNumero.setText("");
        textFieldCEP.setText("");
        textFieldRua.setText("");
        textFieldBairro.setText("");
        textFieldReferencia.setText("");
        comboBoxUF.setSelectedIndex(0);
        comboBoxCidade.setSelectedIndex(0);
    }

    private void configurarBotoes() {
        if (GerenciadorInterfaceGrafica.getInstancia().isEditar()) {
            preencherCampos();
            btnCriar.setText("Editar");
            //btnCriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("imagens/edit.png")));
            btnLimpar.setText("Cancelar");
        }
    }

    private void preencherCampos() {
        usuarioSelecionado = GerenciadorInterfaceGrafica.getInstancia().getUsrSelec();
        textFieldNome.setText(usuarioSelecionado.getNome());
        textFieldCelular.setText(usuarioSelecionado.getCelular());
        textFieldEmail.setText(usuarioSelecionado.getEmail());
        textFieldNumero.setText(String.valueOf(usuarioSelecionado.getNumeroCasa()));
        textFieldCEP.setText(usuarioSelecionado.getCep());
        textFieldRua.setText(usuarioSelecionado.getRua());
        textFieldBairro.setText(usuarioSelecionado.getBairro());
        textFieldReferencia.setText(usuarioSelecionado.getReferencia());
        comboBoxUF.setSelectedItem(usuarioSelecionado.getUf());
        comboBoxCidade.setSelectedItem(usuarioSelecionado.getCidade());
    }

    public String consultarCEP(String cep) throws MalformedURLException, IOException {
        String valido = null;

        // Definir a URL do serviço ViaCEP
        URL url = new URL("https://viacep.com.br/ws/" + cep + "/json/");

        // Definir a URL do serviço GOV.BR
        //URL url = new URL("https://h-apigateway.conectagov.estaleiro.serpro.gov.br/api-cep/v1/consulta/cep/" + cep);
        // Abrir conexão HTTP
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        connection.setRequestMethod("GET");

        // Ler a resposta
        BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        StringBuilder response = new StringBuilder();
        String line;
        while ((line = reader.readLine()) != null) {
            response.append(line);
        }

        // Converter a resposta JSON em um objeto JSONObject
        JSONObject jsonObject = new JSONObject(response.toString());

        // Exibir as informações do endereço
        if (!jsonObject.has("erro")) {

            rua = jsonObject.getString("logradouro");
            bairro = jsonObject.getString("bairro");
            cidade = jsonObject.getString("localidade");
            uf = jsonObject.getString("uf");
            valido = "valido";

        } else {
            System.out.println("CEP não encontrado.");

        }

        // Fechar conexão
        connection.disconnect();
        return valido;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> comboBoxCidade;
    private javax.swing.JComboBox<String> comboBoxUF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCEP;
    private javax.swing.JLabel labelCelular;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel labelFotoEscolher;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelReferencia;
    private javax.swing.JLabel labelRua;
    private javax.swing.JLabel labelUF;
    private javax.swing.JTextField textFieldBairro;
    private javax.swing.JFormattedTextField textFieldCEP;
    private javax.swing.JFormattedTextField textFieldCelular;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JFormattedTextField textFieldNumero;
    private javax.swing.JTextField textFieldReferencia;
    private javax.swing.JTextField textFieldRua;
    // End of variables declaration//GEN-END:variables
}
