/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visao;

import controlador.GerenciadorInterfaceGrafica;
import dominio.Alinhamento;
import dominio.Antecedente;
import dominio.Classe;
import dominio.Personagem;
import dominio.Raca;
import dominio.SubRaca;
import dominio.Usuario;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Caio
 */
public class JDialogNovoPersonagem extends javax.swing.JDialog {

    Usuario usuarioSelecionado;

    /**
     * Creates new form NovoPersonagem
     */
    public JDialogNovoPersonagem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        comboBoxRaca.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Raca racaSelecionada = (Raca) comboBoxRaca.getSelectedItem();
                if (racaSelecionada != null) {
                    List<SubRaca> subracas = GerenciadorInterfaceGrafica.getInstancia().getGerDominio().listarSubRacas(racaSelecionada);
                    comboBoxSubRaca.setModel(new DefaultComboBoxModel(subracas.toArray()));
                }

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spinnerNivel = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        comboBoxClasse = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        comboBoxRaca = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        comboBoxSubRaca = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        comboBoxAntecedente = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        comboBoxAlinhamento = new javax.swing.JComboBox<>();
        labelFotoEscolher = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Novo Personagem");
        jLabel1.setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("Usuário:");

        labelUsuario.setText("Lorem Ipsum");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome:");

        jLabel4.setText("Nível:");

        spinnerNivel.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));

        jLabel5.setText("Classe:");

        comboBoxClasse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Raça:");

        comboBoxRaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Sub-raça:");

        comboBoxSubRaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Antecendente:");

        comboBoxAntecedente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Alinhamento:");

        comboBoxAlinhamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelFotoEscolher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFotoEscolher.setText("Imagem");
        labelFotoEscolher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelFotoEscolher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFotoEscolherMouseClicked(evt);
            }
        });

        jLabel11.setText("Foto");

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        btnAdd.setText("Adcionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxAlinhamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxAntecedente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(labelUsuario)
                        .addGap(5, 5, 5)
                        .addComponent(btnBuscar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxClasse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxRaca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxSubRaca, 0, 198, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelFotoEscolher, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(50, 50, 50))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(179, 179, 179))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(labelUsuario))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(spinnerNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(comboBoxClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelFotoEscolher, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboBoxRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(comboBoxSubRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboBoxAntecedente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboBoxAlinhamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        usuarioSelecionado = GerenciadorInterfaceGrafica.getInstancia().abrirBuscarUsr();
        if (usuarioSelecionado != null)
            labelUsuario.setText(usuarioSelecionado.getNome());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Personagem personagem;
        if (labelUsuario.getText().equals("") || textFieldNome.getText().equals("") || spinnerNivel.getValue() == null || comboBoxClasse.getSelectedItem() == null
                || comboBoxRaca.getSelectedItem() == null || comboBoxSubRaca.getSelectedItem() == null || comboBoxAntecedente.getSelectedItem() == null || comboBoxAlinhamento.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Cadastro de Personagem", JOptionPane.ERROR_MESSAGE);
        } else {
            Usuario mestre = usuarioSelecionado;
            String nome = textFieldNome.getText();
            int nivel = (int) spinnerNivel.getValue();
            Classe classe = (Classe) comboBoxClasse.getSelectedItem();
            SubRaca subRaca = (SubRaca) comboBoxSubRaca.getSelectedItem();
            Antecedente ante = (Antecedente) comboBoxAntecedente.getSelectedItem();
            Alinhamento ali = (Alinhamento) comboBoxAlinhamento.getSelectedItem();
            Icon foto = labelFotoEscolher.getIcon();
            
            personagem = GerenciadorInterfaceGrafica.getInstancia().getGerDominio().inserirPersonagem(mestre, nome, nivel, classe, subRaca, ante, ali, foto);
            JOptionPane.showMessageDialog(this, "Personagem "+ personagem.getIdPer()+ "Inserido com sucesso.", "Cadastro de Personagem", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();
            dispose();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        GerenciadorInterfaceGrafica.getInstancia().carregarCombo(comboBoxClasse, Classe.class);
        GerenciadorInterfaceGrafica.getInstancia().carregarCombo(comboBoxRaca, Raca.class);
        GerenciadorInterfaceGrafica.getInstancia().carregarCombo(comboBoxAntecedente, Antecedente.class);
        GerenciadorInterfaceGrafica.getInstancia().carregarCombo(comboBoxAlinhamento, Alinhamento.class);
    }//GEN-LAST:event_formComponentShown

    private void labelFotoEscolherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFotoEscolherMouseClicked
        JFileChooser janelaArquivo = new JFileChooser();
        janelaArquivo.setMultiSelectionEnabled(false);
        janelaArquivo.setFileFilter(new FileNameExtensionFilter("Imagens", "PNG", "GIF", "JPEG"));
        janelaArquivo.setAcceptAllFileFilterUsed(false);
        if (janelaArquivo.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File arquivo = janelaArquivo.getSelectedFile();
            Icon fotoPerfil = new ImageIcon(arquivo.getPath());
            mostrarImagem(fotoPerfil);
        }
    }//GEN-LAST:event_labelFotoEscolherMouseClicked
    private void mostrarImagem(Icon icon) {
        ImageIcon imagem = (ImageIcon) icon;
        imagem.setImage(imagem.getImage().getScaledInstance(labelFotoEscolher.getWidth(), labelFotoEscolher.getHeight(), Image.SCALE_SMOOTH));
        labelFotoEscolher.setIcon(imagem);
        labelFotoEscolher.setText("");
    }
    
    private void limparCampos() {
    // Limpa o nome
    textFieldNome.setText("");

    // Reseta o nível para o valor mínimo
    spinnerNivel.setValue(1);

    // Reseta os ComboBoxes para o primeiro item (ou remove seleção)
    if (comboBoxClasse.getItemCount() > 0) {
        comboBoxClasse.setSelectedIndex(0);
    }

    if (comboBoxRaca.getItemCount() > 0) {
        comboBoxRaca.setSelectedIndex(0);
    }

    if (comboBoxSubRaca.getItemCount() > 0) {
        comboBoxSubRaca.setSelectedIndex(0);
    }

    if (comboBoxAntecedente.getItemCount() > 0) {
        comboBoxAntecedente.setSelectedIndex(0);
    }

    if (comboBoxAlinhamento.getItemCount() > 0) {
        comboBoxAlinhamento.setSelectedIndex(0);
    }

    // Reseta a imagem do personagem
    labelFotoEscolher.setIcon(null);
    labelFotoEscolher.setText("Imagem");

    // Reseta o label do usuário
    labelUsuario.setText("Lorem Ipsum");

    // Reseta o usuario selecionada
    usuarioSelecionado = null;
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> comboBoxAlinhamento;
    private javax.swing.JComboBox<String> comboBoxAntecedente;
    private javax.swing.JComboBox<String> comboBoxClasse;
    private javax.swing.JComboBox<String> comboBoxRaca;
    private javax.swing.JComboBox<String> comboBoxSubRaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelFotoEscolher;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JSpinner spinnerNivel;
    private javax.swing.JTextField textFieldNome;
    // End of variables declaration//GEN-END:variables
}
